api/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('forum/', views.ForumList.as_view(), name='forumlist_api'),
    path('forum/<int:pk>/', views.ForumDetail.as_view(), name='forumdetail_api'),
    path('topic/', views.TopicList.as_view(), name='topiclist_api'),
    path('topic/<int:pk>/', views.TopicDetail.as_view(), name='topicdetail_api'),
    path('post/', views.PostList.as_view(), name='postlist_api'),
    path('post/<int:pk>/', views.PostDetail.as_view(), name='postdetail_api'),
]

flagship/urls.py
from django.contrib import admin
from django.urls import path, include

"""!!!!THESE 2 from's ARE NECESSARY FOR DEVELOPMENT SERVER!!!!"""
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('gallery/', include('gallery.urls')),
]

urlpatterns += [
    path('forums/', include('forums.urls')),
]

urlpatterns += [
    path('api/', include('api.urls')),
]

"""!!!!THIS IS NECESSARY TO RENDER MEDIA FILES FROM DEVELOPMENT SERVER!!!"""
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

gallery/urls.py
from django.urls import path

from .views import ImageView, ImageList, PhotoBookView, PhotoBookList, ImageCreate

app_name = 'gallery'
urlpatterns = [
    path('', PhotoBookList.as_view(), name='photobooks_list'),
    path('images/', ImageList.as_view(), name='images_list'),
    path('image/<int:pk>/<slug>', ImageView.as_view(), name='image_detail'),
    path('upload/', ImageCreate.as_view(), name='image_upload'),
    path('photobook/<int:pk>/<slug>/', PhotoBookView.as_view(), name='photobook_detail'),
    path('photobook/<int:ppk>/<int:pk>/<slug>', ImageView.as_view(), name='photobook_image_detail')
]

pages/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from iam import views as accounts_views

app_name = 'pages'
urlpatterns = [
    path('', views.home, name='home'),
    path('pages/photohome', views.photohome, name='photohome'),
]

urlpatterns += [
    path('signup/', accounts_views.signup, name='signup'),
    #path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('login/', accounts_views.MyLoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

urlpatterns += [
    path('reset/', auth_views.PasswordResetView.as_view(
        template_name='password_reset.html',
        email_template_name='password_reset_email.html',
        subject_template_name='password_reset_subject.txt'
        ),
    name='password_reset'),
    path('reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
         name='password_reset_complete'),
]

urlpatterns += [
    path('settings/profile/', accounts_views.update_profile, name='my_profile'),
    path('settings/password/', auth_views.PasswordChangeView.as_view(template_name='password_change.html'),
         name='password_change'),
    path('settings/password/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'),
         name='password_change_done'),
]

templates/includes/auth_menu.html
{% if user.is_authenticated %}
	<ul class="navbar-nav ml-auto">
		<li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" href="#" id="userMenu" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				{{ user.username }}
			</a>
			<div class="dropdown-menu dropdown-menu-right w-auto shadow p-0" id="navbarDropdown" aria-labelledby="userMenu">
				<a class="dropdown-item d-flex flex-nowrap align-items-center px-0 py-3" href="{% url 'pages:my_profile' %}">
					<div class="flex-shrink-1 text-center px-3"><ion-icon size="small" name="ios-person"></ion-icon></div>
					<div class="pl-0 pr-4">
						<h6 class="mb-0">My Profile</h6> <small>View your profile and settings</small>
					</div>
				</a>
				<a class="dropdown-item d-flex flex-nowrap align-items-center px-0 py-3" href="{% url 'pages:password_change' %}">
					<div class="flex-shrink-1 text-center px-3"><ion-icon size="small" name="ios-lock"></ion-icon></div>
					<div class="pl-0 pr-4">
						<h6 class="mb-0">Change Password</h6> <small>Reset your password</small>
					</div>
				</a>	
				<div class="dropdown-divider"></div>
				<a class="dropdown-item d-flex flex-nowrap align-items-center px-0 py-3" href="{% url 'pages:logout' %}">
					<div class="flex-shrink-1 text-center px-3"><ion-icon size="small" name="ios-log-out"></ion-icon></div>
					<div class="pl-0 pr-4">
						<h6 class="mb-0">Logout</h6> <small>Sign out</small>
					</div>
				</a>
			</div>
		</li>
	</ul>			
{% else %}
	<form class="form-inline ml-auto">
		<a href="{% url 'pages:signup' %}" class="btn btn-secondary-outline btn-sm">Sign up</a>
		<a href="{% url 'pages:login' %}" class="btn btn-light-outline btn-sm ml-2">Log in</a>
	</form>
{% endif %}

templates/includes/footer.html
{% load static %}

<footer id="footer">
	<div class="container-fluid py5">
		<div class="container">
			<div class="row">
					<!-- Grid column -->
				<div class="col-md-6 text-center">
					<h6 class="text-uppercase">Digital Fusion Software Group</h6>
					<div class="container ">
						<img class="img-fluid" alt='' width=75 height=75 src="{% static 'img/digitalfacets_logo_v2_500x500.png' %}">
					</div>
					<p><small>Innovation | Creativity | Multi<span class="wide-space footer-text-emphasize">facet</span>ed</small></p>
				</div>
				<!-- Grid column -->
				
				
				<!-- Grid column -->
				<div class="col">
					<h6 class="text-uppercase">Site</h6>
					<ul class="list-unstyled">
						<li>
							<a href="#!">Portfolio</a>
						</li>
						<li>
							<a href="#!">Blog</a>
						</li>
						<li>
							<a href="#!">Discourse</a>
						</li>
						<li>
							<a href="#!">Photography</a>
						</li>
					</ul>
				</div>
				<!-- Grid column -->
				
				
				<!-- Grid column -->
				<div class="col">
					<h6 class="text-uppercase">Follow</h6>
					<ion-icon ios="logo-twitter" md="logo-twitter" class="footer-icon"></ion-icon>&nbsp;<ion-icon ios="logo-snapchat" md="logo-snapchat" class="footer-icon"></ion-icon>&nbsp;<ion-icon ios="logo-github" md="logo-github" class="footer-icon"></ion-icon>&nbsp;<ion-icon ios="logo-instagram" md="logo-instagram" class="footer-icon"></ion-icon>
				</div>
				<!-- Grid column -->
				
			</div>
			
			<!-- Copyright -->
			<span class="float-right text-muted small">
				Copyright &copy; {% now "Y" %} <strong>DigitalFacets</strong>. All Rights Reserved.
			</span>
			<!-- Copyright -->
		</div>
	</div>
</footer>

templates/includes/form.html
{% load form_tags widget_tweaks %}

{% if form.non_field_errors %}
	<div class="alert alert-danger" role="alert">
		{% for error in form.non_field_errors %}
			<p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
		{% endfor %}
	</div>
{% endif %}

{% for field in form %}
	<div class="form-group">
		{{ field.label_tag }}
		{% render_field field class=field|input_class %}
		{% for error in field.errors %}
			<div class="invalid-feedback">
				{{ error }}
			</div>
		{% endfor %}
		{% if field.help_text %}
			<small class="form-text text-muted">
				{{ field.help_text|safe }}
			</small>
		{% endif %}
	</div>
{% endfor %}

templates/includes/header.html
{% load static %}

<nav class="navbar navbar-expand-lg fixed-top">
	<div class="container">
		<img class="img-fluid" alt='' width=39 height=55 src="{% static 'img/digitalfacets_logo_v1_500x505.png' %}">&nbsp;&nbsp;
		<a class="navbar-brand" href="{% url 'pages:home' %}">Digital Facets</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="mainMenu">
			<ul class="navbar-nav">
				<li class="nav-item active">
					<a class="nav-link" href="{% url 'pages:home' %}">Home</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#">Portfolio</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#">Blog</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'forum_home' %}">Discourse</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#">Photography</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#">About Us</a>
				</li>
			</ul>
			
			<!-- Show/Hide personal menu -->
			{% include 'includes/auth_menu.html' %}
			
		</div>
	</div>
</nav>

templates/includes/image_upload_form.html
{% load form_tags widget_tweaks %}

{% if form.non_field_errors %}
	<div class="alert alert-danger" role="alert">
		{% for error in form.non_field_errors %}
			<p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
		{% endfor %}
	</div>
{% endif %}

{% include 'includes/messages.html' %}

<form method="post" id="image_upload_form" action="{% url 'gallery:image_upload' %}" enctype="multipart/form-data">
	{% csrf_token %}
	
	<input id="data" type="file" name="data" data-url="{% url 'gallery:image_upload' %}" multiple>
	
	<input type="hidden" name="ppk" value="{{ photobook.pk }}"/>
	<input type="hidden" name="next" value="{{ request.path }}"/>
</form>

templates/includes/messages.html
{% for message in messages %}
	<div class="alert {{ message.tags }} alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
		{{ message }}
	</div>
{% endfor %}

templates/includes/pagination.html
{% if is_paginated %}
	<nav aria-label="Pagination" class="mb-4">
		<ul class="pagination">
			{% if page_obj.number > 1 %}
				<li class="page-item">
					<a class="page-link" href="?page=1">First</a>
				</li>
			{% else %}
				<li class="page-item disabled">
					<span class="page-link">First</span>
				</li>
			{% endif %}
			
			{% if page_obj.has_previous %}
				<li class="page-item">
					<a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
				</li>
			{% else %}
				<li class="page-item disabled">
					<span class="page-link">Previous</span>
				</li>
			{% endif %}
			
			{% for page_num in paginator.page_range %}
				{% if page_obj.number == page_num %}
					<li class="page-item active">
						<span class="page-link">
							{{ page_num }}
							<span class="sr-only">(current)</span>
						</span>
					</li>
				{% elif page_num > page_obj.number|add:'-3' and page_num < page_obj.number|add:'3' %}
					<li class="page-item">
						<a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
					</li>
				{% endif %}
			{% endfor %}
			
			{% if page_obj.has_next %}
				<li class="page-item">
					<a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
				</li>
			{% else %}
				<li class="page-item disabled">
					<span class="page-link">Next</span>
				</li>
			{% endif %}
			
			{% if page_obj.number != paginator.num_pages %}
				<li class="page-item">
					<a class="page-link" href="?page={{ paginator.num_pages }}">Last</a>
				</li>
			{% else %}
				<li class="page-item disabled">
					<span class="page-link">Last</span>
				</li>
			{% endif %}
		</ul>
	</nav>
{% endif %}

templates/includes/pagintation.html
{% if is_paginated %}
	<nav aria-label="Pagination" class="mb-4">
		<ul class="pagination">
			{% if page_obj.number > 1 %}
				<li class="page-item">
					<a class="page-link" href="?page=1">First</a>
				</li>
			{% else %}
				<li class="page-item disabled">
					<span class="page-link">First</span>
				</li>
			{% endif %}
			
			{% if page_obj.has_previous %}
				<li class="page-item">
					<a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
				</li>
			{% else %}
				<li class="page-item disabled">
					<span class="page-link">Previous</span>
				</li>
			{% endif %}
			
			{% for page_num in paginator.page_range %}
				{% if page_obj.number == page_num %}
					<li class="page-item active">
						<span class="page-link">
							{{ page_num }}
							<span class="sr-only">(current)</span>
						</span>
					</li>
				{% elif page_num > page_obj.number|add:'-3' and page_num < page_obj.number|add:'3' %}
					<li class="page-item">
						<a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
					</li>
				{% endif %}
			{% endfor %}
			
			{% if page_obj.has_next %}
				<li class="page-item">
					<a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
				</li>
			{% else %}
				<li class="page-item disabled">
					<span class="page-link">Next</span>
				</li>
			{% endif %}
			
			{% if page_obj.number != paginator.num_pages %}
				<li class="page-item">
					<a class="page-link" href="?page={{ paginator.num_pages }}">Last</a>
				</li>
			{% else %}
				<li class="page-item disabled">
					<span class="page-link">Last</span>
				</li>
			{% endif %}
		</ul>
	</nav>
{% endif %}

templates/includes/thumbnail.html
<div class="thumbnail">
	<img id="image_{{ image.pk }}" class="image" alt="{{ image.title }}" data-src="{{ image.data_thumbnail.url }}" style="width: {% widthratio image.data_thumbnail.width 2 1 %}px;margin-right: {{ image_margin }}px"/>
	<div class="overlay">
		<div class="label"> {{ image.title }} </div>
	</div>
</div>

templates/includes/thumbnail_empty.html
{% load static %}

<div class="thumbnail">
	<img id="image_{{ forloop.counter0 }}" class="image empty" alt="{{ album.title }}" data-src="{% static 'img/album.png' %}" style="margin-right: {{ image_margin }}px"/>
	<div class="overlay">
		<div class="label"> {{ photobook.title }} </div>
	</div>
</div>

templates/includes/thumbnail_preview.html
<div class="thumbnail" style="display: block">
	<img id="image_{{ image.pk }}" class="image" alt="{{ image.title }}" src="{{ image.data_thumbnail.url }}"/>
	<div class="overlay">
		<div class="label preview"> {{ image.title }} </div>
	</div>
</div>