api/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('forum/', views.ForumList.as_view(), name='forumlist_api'),
    path('forum/<int:pk>/', views.ForumDetail.as_view(), name='forumdetail_api'),
    path('topic/', views.TopicList.as_view(), name='topiclist_api'),
    path('topic/<int:pk>/', views.TopicDetail.as_view(), name='topicdetail_api'),
    path('post/', views.PostList.as_view(), name='postlist_api'),
    path('post/<int:pk>/', views.PostDetail.as_view(), name='postdetail_api'),
]

flagship/urls.py
from django.contrib import admin
from django.urls import path, include

"""!!!!THESE 2 from's ARE NECESSARY FOR DEVELOPMENT SERVER!!!!"""
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('gallery/', include('gallery.urls')),
]

urlpatterns += [
    path('forums/', include('forums.urls')),
]

urlpatterns += [
    path('api/', include('api.urls')),
]

"""!!!!THIS IS NECESSARY TO RENDER MEDIA FILES FROM DEVELOPMENT SERVER!!!"""
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

forums/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.ForumListView.as_view(), name='forum_home'),
    path('<int:pk>/', views.TopicListView.as_view(), name='forum_topics'),
    path('<int:pk>/new/', views.new_topic, name='new_topic'),
    path('<int:pk>/topics/<int:topic_pk>/', views.PostListView.as_view(), name='topic_posts'),
    path('<int:pk>/topics/<int:topic_pk>/reply/', views.reply_topic, name='reply_topic'),
    path('<int:pk>/topics/<int:topic_pk>/posts/<int:post_pk>/edit/', views.PostUpdateView.as_view(), name='edit_post'),
]

gallery/urls.py
from django.urls import path

from .views import ImageView, ImageList, PhotoBookView, PhotoBookList, ImageCreate

app_name = 'gallery'
urlpatterns = [
    path('', PhotoBookList.as_view(), name='photobooks_list'),
    path('images/', ImageList.as_view(), name='images_list'),
    path('image/<int:pk>/<slug>', ImageView.as_view(), name='image_detail'),
    path('upload/', ImageCreate.as_view(), name='image_upload'),
    path('photobook/<int:pk>/<slug>/', PhotoBookView.as_view(), name='photobook_detail'),
    path('photobook/<int:ppk>/<int:pk>/<slug>', ImageView.as_view(), name='photobook_image_detail')
]

pages/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from iam import views as accounts_views

app_name = 'pages'
urlpatterns = [
    path('', views.home, name='home'),
    path('pages/photohome', views.photohome, name='photohome'),
]

urlpatterns += [
    path('signup/', accounts_views.signup, name='signup'),
    #path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('login/', accounts_views.MyLoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

urlpatterns += [
    path('reset/', auth_views.PasswordResetView.as_view(
        template_name='password_reset.html',
        email_template_name='password_reset_email.html',
        subject_template_name='password_reset_subject.txt'
        ),
    name='password_reset'),
    path('reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
         name='password_reset_complete'),
]

urlpatterns += [
    path('settings/profile/', accounts_views.update_profile, name='my_profile'),
    path('settings/password/', auth_views.PasswordChangeView.as_view(template_name='password_change.html'),
         name='password_change'),
    path('settings/password/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'),
         name='password_change_done'),
]

forums/models.py
import math

from django.db import models
from django.contrib.auth.models import User
from django.db import models
from django.utils.html import mark_safe
from django.utils.text import Truncator

from markdown import markdown

# Create your models here.
class Forum(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name
    
    def get_posts_count(self):
        return Post.objects.filter(topic__forum=self).count()
    
    def get_last_post(self):
        return Post.objects.filter(topic__forum=self).order_by('-created_at').first()
    
    
class Topic(models.Model):
    subject = models.CharField(max_length=255)
    last_updated = models.DateTimeField(auto_now_add=True)
    forum = models.ForeignKey(Forum, on_delete=models.PROTECT, related_name='topics')
    creator = models.ForeignKey(User, on_delete=models.PROTECT, related_name='topics')
    views = models.PositiveIntegerField(default=0)
    
    def __str__(self):
        return self.subject
    
    def get_page_count(self):
        count = self.posts.count()
        pages = count / 20
        return math.ceil(pages)
    
    def has_many_pages(self, count=None):
        if count is None:
            count = self.get_page_count()
        return count > 6
    
    def get_page_range(self):
        count = self.get_page_count()
        if self.has_many_pages(count):
            return range(1, 5)
        return range(1, count + 1)
    
    def get_last_ten_posts(self):
        return self.posts.order_by('-created_at')[:10]
    
    

class Post(models.Model):
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(Topic, on_delete=models.PROTECT, related_name='posts')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT, related_name='posts')
    updated_by = models.ForeignKey(User, null=True, on_delete=models.PROTECT, related_name='+')
    
    def __str__(self):
        truncated_message = Truncator(self.message)
        return truncated_message.chars(30)
    
    def get_message_as_markdown(self):
        return mark_safe(markdown(self.message, safe_mode='escape'))

forums/forms.py
from django import forms

from .models import Post, Topic


class NewTopicForm(forms.ModelForm):
    message = forms.CharField(
        widget=forms.Textarea(
            attrs={'rows': 5, 'placeholder': "What's on your mind?"}
        ),
        max_length=4000,
        help_text='The max length of the text is 4000.'
    )
    
    class Meta:
        model = Topic
        fields = ['subject', 'message']
        
        
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['message', ]

forums/views.py
from django.db.models import Count
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import UpdateView, ListView
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.urls import reverse
from rest_framework import generics

from .forms import NewTopicForm, PostForm
from .models import Forum, Topic, Post

# Create your views here.
class ForumListView(ListView):
    model = Forum
    context_object_name = 'forums'
    template_name = 'forums.html'
    
class TopicListView(ListView):
    model = Topic
    context_object_name = 'topics'
    template_name = 'forum_topics.html'
    paginate_by = 20
    
    def get_context_data(self, **kwargs):
        kwargs['forum'] = self.forum
        return super().get_context_data(**kwargs)
    
    def get_queryset(self):
        self.forum = get_object_or_404(Forum, pk=self.kwargs.get('pk'))
        queryset = self.forum.topics.order_by('-last_updated').annotate(replies=Count('posts') - 1)
        return queryset

class PostListView(ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'forum_topic_posts.html'
    paginate_by = 20

    def get_context_data(self, **kwargs):
        session_key = 'viewed_topic_{}'.format(self.topic.pk)
        if not self.request.session.get(session_key, False):
            self.topic.views += 1
            self.topic.save()
            self.request.session[session_key] = True
        kwargs['topic'] = self.topic
        return super().get_context_data(**kwargs)
    
    def get_queryset(self):
        self.topic = get_object_or_404(Topic, forum__pk=self.kwargs.get('pk'), pk=self.kwargs.get('topic_pk'))
        queryset = self.topic.posts.order_by('created_at')
        return queryset
    

@login_required
def new_topic(request, pk):
    forum = get_object_or_404(Forum, pk=pk)
    if request.method == 'POST':
        form = NewTopicForm(request.POST)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.forum = forum
            topic.creator = request.user
            topic.save()
            Post.objects.create(
                message=form.cleaned_data.get('message'),
                topic=topic,
                created_by=request.user
            )
            return redirect('topic_posts', pk=pk, topic_pk=topic.pk)
    else:
        form = NewTopicForm()
    return render(request, 'new_forum_topic.html', {'forum': forum, 'form': form})


@login_required
def reply_topic(request, pk, topic_pk):
    topic = get_object_or_404(Topic, forum__pk=pk, pk=topic_pk)
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.topic = topic
            post.created_by = request.user
            post.save()
            
            topic.last_updated = timezone.now()
            topic.save()
            topic_url = reverse('topic_posts', kwargs={'pk': pk, 'topic_pk': topic_pk})
            topic_post_url = '{url}?page={page}#{id}'.format(
                url=topic_url,
                id=post.pk,
                page=topic.get_page_count()
            )
            
            return redirect(topic_post_url)
    else:
        form = PostForm()
    return render(request, 'reply_forum_topic.html', {'topic': topic, 'form': form})


@method_decorator(login_required, name='dispatch')
class PostUpdateView(UpdateView):
    model = Post
    fields = ('message', )
    template_name = 'edit_forum_post.html'
    pk_url_kwarg = 'post_pk'
    context_object_name = 'post'
    
    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(created_by=self.request.user)
    
    def form_valid(self, form):
        post = form.save(commit=False)
        post.updated_by = self.request.user
        post.updated_at = timezone.now()
        post.save()
        return redirect('topic_posts', pk=post.topic.forum.pk, topic_pk=post.topic.pk)
    

    

templates/base_gallery.html
{% load static %}<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>{% block title %}Digital Facets{% endblock %}</title>
		<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<link href="https://fonts.googleapis.com/css?family=Open+Sans|Lato&display=swap&text=Digital%20Facets" rel="stylesheet">
		<link href="https://cdnjs.cloudflare.com/ajax/libs/simplemde/1.11.2/simplemde.min.css" rel="stylesheet">
		<link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.css" rel="stylesheet">
		<link rel="stylesheet" href="{% static 'css/app.css' %}">
		<link rel="stylesheet" href="{% static 'css/gallery.css' %}">
		{% block stylesheet %}
		{% endblock %}
		{% block head %}
		{% endblock %}
	</head>
	<body>
		{% block body %}
			<!-- Header -->
			<nav id="galleryNav" class="navbar navbar-expand-lg fixed-top">
				<div class="container">
					<img class="img-fluid" alt='' width=39 height=55 src="{% static 'img/digitalfacets_logo_v1_500x505.png' %}">&nbsp;&nbsp;
					<a class="navbar-brand" href="{% url 'pages:home' %}">Digital Facets</a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#galleryMenu" aria-controls="galleryMenu" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse" id="galleryMenu">
						<ul class="navbar-nav">
							<li class="nav-item">
								{% block bar_title %}
									<div id="title">Photobooks</div>
								{% endblock %}
							</li>
						</ul>
						
						<!-- Show/Hide personal menu -->
						{% include 'includes/auth_menu.html' %}
					</div>
				</div>
			</nav>
			<!-- End Header -->
			<div class="wrapper">
				<!-- Body -->
					<div id="content" class="container">
						{% block page_content %}
						{% endblock %}
					</div>
				<!-- End Body -->
				<!-- Footer -->
				{% block page_footer %}
				{% endblock %}
				<!--End Footer -->
			</div>
		{% endblock body %}
		
		<script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.15.0/popper.min.js"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.4/js/tether.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/simplemde/1.11.2/simplemde.min.js"></script>
		<script src="https://unpkg.com/ionicons@4.5.5/dist/ionicons.js"></script>
				
		{% block javascript %}
		{% endblock %}
	</body>
</html>

templates/image_detail.html
{% extends 'base_gallery.html' %}

{% load static %}

{% block stylesheet %}
	<style>
		#content {
			padding-bottom: 0;
			width: 100%;
		}
	</style>
{% endblock %}

{% block title %}
{% if photobook %}{{ photobook.title }} - {% endif %}{{ image.title }}
{% endblock %}

{% block bar_title %}
<div id="title">{% if photobook %}<a href="{% url 'gallery:photobooks_list' %}"><small>PhotoBooks</small></a> - <a href="{% url 'gallery:photobook_detail' photobook.pk photobook.slug  %}"><small>{{ photobook.title }}</small></a> - {% endif %}{{ image.title }}</div>
{% endblock %}

{% block page_content %}
<div class="row">
	<div id="image_detail" class="col-lg-12 text-center">
		<a href="#galleryModal" data-toggle="modal" data-src="{{ image.data.url }}" data-id="{{ image.title }}" data-alt="{{ image.caption }}">
			<img id="image_preview" class="img-fluid" src="{{ image.data.url }}" alt="{{ image.title }}"/>
		</a>
		<div id="photobook_preview_box" class="d-inline-flex align-items-center">
			<ion-icon name="arrow-back" size="large"></ion-icon>
			<div id="photobook_preview">
				{% if photobook_images %}
					{% for image in photobook_images %}
						<a href="{% url 'gallery:photobook_image_detail' ppk image.pk image.slug %}#image_{{ image.pk }}" style="display: inline-block;">
							<div class="thumbnail_preview" style="display: block">
								<img id="image_{{ image.pk }}" class="img-fluid" alt="{{ image.title}}" src="{{ image.data_thumbnail.url }}"/>
								<div class="overlay">
									<div class="label preview"> {{ image.title }} </div>
								</div>
							</div>
						</a>
					{% endfor %}
				{% elif photobooks %}
					{% for photobook in photobooks %}
						{% with photobook.display_highlight as image %}
							<a href="{% url 'gallery:photobook_detail' photobook.pk photobook.slug %}" style="display: inline-block;">
								<div class="thumbnail_preview" style="display: block">
									<img id="image_{{ image.pk }}" class="img-fluid" alt="{{ image.title}}" src="{{ image.data_thumbnail.url }}"/>
									<div class="overlay">
										<div class="label preview"> {{ image.title }} </div>
									</div>
								</div>
							</a>
						{% endwith %}
					{% endfor %}
				{% endif %}
			</div>
			<ion-icon name="arrow-forward" size="large"></ion-icon>
		</div>
	</div>
</div>
<div id="galleryModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-xl">
        <div id="modalGallery" class="modal-content">
            <div class="modal-body text-center">
            	<div class="container-fluid">
	            	<div class="row">
	            		<div class="col-12">
			                <img src="" id="galleryImage" class="center-block img-fluid">
		                </div>
                	</div>
                </div>
            </div>
            <div class="modal-footer">
            	<div class="container">
            		<div class="float-left mh-100 text-primary" style="height: 40px;">
            			<span id="galleryImageName"></span><br/>
            			<small><span id="galleryImageCaption"></span></small>
            		</div>
            		<div class="float-right">
	            		<button class="btn btn-secondary-outline btn-lg" data-dismiss="modal" aria-hidden="true">Close <ion-icon name="close"></ion-icon></button>
	            	</div>
            	</div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block javascript %}
<!-- Inline JScript to determine previous and next image urls -->
<script type="text/javascript">
	{% if previous_image %}
		previous_image_url = "{% url 'gallery:photobook_image_detail' ppk previous_image.pk previous_image.slug %}#image_{{ previous_image.pk }}";
	{% endif %}
	
	{% if next_image %}
		next_image_url = "{% url 'gallery:photobook_image_detail' ppk next_image.pk next_image.slug %}#image_{{ next_image.pk }}";
	{% endif %}
	
	/* Provide navigation keys to change the current image */
	var left = 37; var right = 39;
	document.addEventListener("keydown", function(event) {
		switch(event.which) {
			case left:
				if (previous_image_url) {
					window.location.href = previous_image_url;
				}
			break;
			case right:
				if (next_image_url) {
					window.location.href = next_image_url;
				}
			break;
			default: return;
		}
		event.preventDefault();
	});
	
	<!-- JQuery to load gallery Modal w/ the active photo -->
	$('#galleryModal').on('show.bs.modal', function (e) {
		$('#galleryImage').attr("src",$(e.relatedTarget).data("src"));
		$('#galleryImageName').text($(e.relatedTarget).data("id"));
		$('#galleryImageCaption').text($(e.relatedTarget).data("alt"));
	});
</script>
{% endblock %}

templates/image_list_LEGACY.html
{% extends 'base_gallery.html' %}

{% load static %}

{% block bar_title %}
	<div id="title">Photobooks</div>
{% endblock %}

{% block page_content %}
	{% include "includes/image_upload_form.html" %}
	
	<div id="image_container" class="debugBorder">
		{% for image in images_list %}
			<a href="{% url 'gallery:image_detail' image.pk image.slug %}">
				{% include "includes/thumbnail.html" %}
			</a>
		{% endfor %}
		
		{% if not images_list and user.is_authenticated %}
			<div id="empty_placeholder">
				Drag images here to upload to the image feed
			</div>
		{% endif %}
	</div>
{% endblock %}

{% block javascript %}
	<script type="text/javascript" src="{% static 'js/image_upload.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/infinite_scroll.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/justify_images.js' %}"></script>
{% endblock %}

templates/login.html
{% extends 'base_iam.html' %}

{% block title %}Sign In to Digital Facets{% endblock %}

{% block page_content %}
	<div class="row justify-content-center">
		<div class="col-lg-4 col-md-6 col-sm-8">
			<div class="card">
				<div class="card-body">
					<h3 class="card-title">Sign In</h3>
					<form id="loginform" method="post" novalidate>
						{% csrf_token %}
						<input type="hidden" name="next" value="{{ next }}">
						{% include 'includes/form.html' %}
						<button type="submit" class="btn btn-info btn-block">Sign In</button>
						
						<!-- Google RECAPTCHA Implementation --!>
						<input type="hidden" name="g-recaptcha-response" id="g-recaptcha-response">
						<script src='https://www.google.com/recaptcha/api.js?render={{ RECAPTCHA_SITE_KEY }}'></script>
						<script type="text/javascript">
							grecaptcha.ready(function() {
								$('#loginform').submit(function(e){
									var form = this;
									e.preventDefault()
									grecaptcha.execute('{{ RECAPTCHA_SITE_KEY }}', {action: 'login'}).then(function(token) {
										$('#g-recaptcha-response').val(token)
										form.submit()
									});
								})
							});
						</script>
						<!-- End Google RECAPTCHA Implementation -->
						
					</form>
				</div>
				<div class="card-footer text-muted text-center">
					New to the site? <a href="{% url 'pages:signup' %}">Sign Up</a>
				</div>
			</div>
			<div class="text-center py-2">
				<small>
					<a href="{% url 'pages:password_reset' %}" class="text-muted">Forgot your password?</a>
				</small>
			</div>
		</div>
	</div>
{% endblock %}

templates/my_profile.html
{% extends 'base_iam.html' %}

{% block title %}My Profile{% endblock %}

{% block breadcrumb %}
	<li class="breadcrumb-item active">My Profile</li>
{% endblock %}

{% block page_content %}
	<div class="row justify-content-center">
		<div class="col-lg-6 col-md-8 col-sm-10">
			<form method="post" novalidate>
				{% csrf_token %}
				{% include 'includes/form.html' %}
				<button type="submit" class="btn btn-success">Save Changes</button>
			</form>
		</div>
	</div>
{% endblock %}

templates/photobook_detail.html
{% extends 'base_gallery.html' %}

{% load static auth_extras %}

{% block bar_title %}
<div id="title"><a href="{% url 'gallery:photobooks_list' %}"><small>PhotoBooks</small></a> - {{ photobook.title }}</div>
{% endblock %}

{% block page_content %}
<div class="row">
	<div id="messages_wrapper" class="col-lg-12 text-center">
		{% if user.is_authenticated and user.is_superuser or user|has_group:"Power User" %}
			{% include "includes/image_upload_form.html" %}
		{% endif %}
	</div>
	<div id="image_container" class="col-lg-12 text-center">
		{% for image in images %}
			<a href="{% url 'gallery:photobook_image_detail' photobook.pk image.pk image.slug %}#image_{{ image.pk }}">
				<div class="thumbnail">
					<img id="image_{{ image.pk }}" class="img-fluid image" alt="{{ image.title}}" data-src="{{ image.data_thumbnail.url }}" src="{{ image.data_thumbnail.url }}"/>
					<div class="overlay">
						<div class="label"> {{ image.title }} </div>
					</div>
				</div>
			</a>
		{% endfor %}
		
		{% if user.is_authenticated and user.is_superuser or user|has_group:"Power User" %}
			{% if not photobook.images.all %}
				<div id="empty_placeholder">
					<p>Drag images here to upload to the photobook</p>
				</div>
			{% endif %}
		{% endif %}
	</div>
</div>
<div class="container bottom-padding-minor">
</div>
{% endblock %}

{% block page_footer %}
{% include 'includes/footer.html' %}
{% endblock %}

{% block javascript %}
<script type="text/javascript" src="{% static 'js/image_upload.js' %}"></script>
<script type="text/javascript" src="{% static 'js/infinite_scroll.js' %}"></script>
{% endblock %}

templates/photobook_detail_LEGACY.html
{% extends 'base_gallery.html' %}

{% load static %}

{% block bar_title %}
	<div id="title"> {{ photobook.title }} </div>
{% endblock %}

{% block page_content %}
	{% include "includes/image_upload_form.html" %}

	<div id="image_container" class="debugBorder">
		{% for image in images %}
			<a href="{% url 'gallery:photobook_image_detail' photobook.pk image.pk image.slug %}#image_{{ image.pk }}">
				{% include "includes/thumbnail.html" %}
			</a>
		{% endfor %}
		
		{% if not photobook.images.all and user.is_authenticated %}
			<div id="empty_placeholder">
				Drag images here to upload to the photobook
			</div>
		{% endif %}
	</div>
	
{% endblock %}

{% block javascript %}
	<script type="text/javascript" src="{% static 'js/image_upload.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/infinite_scroll.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/justify_images.js' %}"></script>
{% endblock %}

templates/photobook_list_LEGACY.html
{% extends 'base_gallery.html' %}

{% load static %}

{% block bar_title %}
	<div id="title">DF Photobooks</div>
{% endblock %}

{% block page_content %}
	<div id="image_container" class="debugBorder">
		{% for photobook in photobooks_list %}
			<a href="{% url 'gallery:photobook_detail' photobook.pk photobook.slug %}">
				{% if photobook.display_highlight %}
					{% with photobook.display_highlight as image %}
						 {% include "includes/thumbnail.html" %}
					{% endwith %}
				{% else %}
					{% include "includes/thumbnail_empty.html" %}
				{% endif %}
			</a>
		{% endfor %}
	</div>
{% endblock %}

{% block javascript %}
	<script type="text/javascript" src="{% static 'js/infinite_scroll.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/justify_images.js' %}"></script>
{% endblock %}

templates/signup.html
{% extends 'base_iam.html' %}

{% block title %}Digital Facets - Join Today{% endblock %}

{% block page_content %}
	<div class="row justify-content-center">
		<div class="col-lg-6 col-md-8 col-sm-12">
			<div class="card">
				<div class="card-body">
					<h3 class="card-title">Sign Up</h3>
					<form id="signupform" method="post" novalidate>
						{% csrf_token %}
						{% include 'includes/form.html' %}
						<button type="submit" class="btn btn-info btn-block">Create an Account</button>
						
						<!-- Google RECAPTCHA Implementation --!>
						<input type="hidden" name="g-recaptcha-response" id="g-recaptcha-response">
						<script src='https://www.google.com/recaptcha/api.js?render={{ RECAPTCHA_SITE_KEY }}'></script>
						<script type="text/javascript">
							grecaptcha.ready(function() {
								$('#signupform').submit(function(e){
									var form = this;
									e.preventDefault()
									grecaptcha.execute('{{ RECAPTCHA_SITE_KEY }}', {action: 'signup'}).then(function(token) {
										$('#g-recaptcha-response').val(token)
										form.submit()
									});
								})
							});
						</script>
						<!-- End Google RECAPTCHA Implementation -->
						
					</form>
				</div>
				<div class="card-footer text-muted text-center">
					Already have an account? <a href="{% url 'pages:login' %}">Log in</a>
				</div>
			</div>
		</div>
	</div>
{% endblock %}